import { describe, expect, test } from 'bun:test';

import { collectTerminalUrlSegments, findTerminalUrlAtCell } from './terminal-link';

describe('collectTerminalUrlSegments', () => {
  test('returns single-line url segment', () => {
    const rawLines = ['open https://example.com/path/to/resource'];
    const matches = collectTerminalUrlSegments(rawLines, 0, rawLines.length, 80);

    expect(matches).toHaveLength(1);
    expect(matches[0].url).toBe('https://example.com/path/to/resource');
    expect(matches[0].segments).toEqual([
      {
        lineIdx: 0,
        startCol: 5,
        endCol: 'open https://example.com/path/to/resource'.length,
      },
    ]);
  });

  test('reconstructs and segments wrapped urls across lines', () => {
    const rawLines = [
      'https://example.com/very',
      'longsegmentthatcontinues',
    ];

    const matches = collectTerminalUrlSegments(rawLines, 0, rawLines.length, 20);

    expect(matches).toHaveLength(1);
    expect(matches[0].url).toBe('https://example.com/verylongsegmentthatcontinues');
    expect(matches[0].segments).toEqual([
      {
        lineIdx: 0,
        startCol: 0,
        endCol: 24,
      },
      {
        lineIdx: 1,
        startCol: 0,
        endCol: 24,
      },
    ]);
  });

  test('trims trailing punctuation from matched url', () => {
    const rawLines = ['check https://example.com/path.'];
    const matches = collectTerminalUrlSegments(rawLines, 0, 1, 80);

    expect(matches).toHaveLength(1);
    expect(matches[0].url).toBe('https://example.com/path');
    expect(matches[0].segments).toEqual([
      {
        lineIdx: 0,
        startCol: 6,
        endCol: 6 + 'https://example.com/path'.length,
      },
    ]);
  });

  test('continuation stops at a new scheme (a)', () => {
    const a = collectTerminalUrlSegments(
      ['https://a.example.com/xxxxxxxxxxxxxxxx', 'https://b.example.com/y'],
      0,
      2,
      36,
    );
    expect(a).toEqual([
      {
        url: 'https://a.example.com/xxxxxxxxxxxxxxxx',
        segments: [{ lineIdx: 0, startCol: 0, endCol: 38 }],
      },
      {
        url: 'https://b.example.com/y',
        segments: [{ lineIdx: 1, startCol: 0, endCol: 23 }],
      },
    ]);

    const b = collectTerminalUrlSegments(
      ['https://example.com/redir?to=aaaaaaa', 'https://target.example.com/final'],
      0,
      2,
      36,
    );
    expect(b).toEqual([
      {
        url: 'https://example.com/redir?to=aaaaaaa',
        segments: [{ lineIdx: 0, startCol: 0, endCol: 36 }],
      },
      {
        url: 'https://target.example.com/final',
        segments: [{ lineIdx: 1, startCol: 0, endCol: 32 }],
      },
    ]);
  });

  /**
   * Fixed-width wrap like a real tmux pane: each row is at most `cols` wide.
   * Hand-built rows longer than `cols` are invalid inputs for wrap tests.
   */
  function wrapFixedWidth(text: string, cols: number): string[] {
    const rows: string[] = [];
    for (let i = 0; i < text.length; i += cols) {
      rows.push(text.slice(i, i + cols));
    }
    for (const row of rows) {
      expect(row.length).toBeLessThanOrEqual(cols);
    }
    return rows;
  }

  function mainUrl(matches: { url: string }[]): string | undefined {
    // Prefer the longest match (the reconstructed multi-segment URL when present).
    return matches.map((m) => m.url).sort((a, b) => b.length - a.length)[0];
  }

  describe('scheme-break: both directions pinned', () => {
    // Direction A — single URL with embedded unencoded scheme must survive every wrap width.
    // Corpus is generated by fixed-width wrapping (tmux-realistic), not hand-built over-wide rows.
    const OAUTH_LINE =
      'open https://auth.example.com/authorize?redirect_uri=https://app.example.com/cb&state=xyz';
    const OAUTH_URL =
      'https://auth.example.com/authorize?redirect_uri=https://app.example.com/cb&state=xyz';

    test('embedded-scheme OAuth URL: wrap-sweep cols 20-120 reconstructs full URL', () => {
      let widthsTested = 0;
      let schemeLeadingContinuations = 0;

      for (let cols = 20; cols <= 120; cols++) {
        const lines = wrapFixedWidth(OAUTH_LINE, cols);
        // Only widths that actually wrap the line exercise continuation logic.
        if (lines.length < 2) continue;
        widthsTested++;

        // Count widths where some continuation row begins with a scheme (the regression shape).
        for (let i = 1; i < lines.length; i++) {
          if (/^https?:\/\//.test(lines[i].trimStart())) schemeLeadingContinuations++;
        }

        const matches = collectTerminalUrlSegments(lines, 0, lines.length, cols);
        expect(mainUrl(matches)).toBe(OAUTH_URL);
      }

      expect(widthsTested).toBeGreaterThan(0);
      // cols=53 is the measured regression: row 2 begins with https://app…
      const cols53 = wrapFixedWidth(OAUTH_LINE, 53);
      expect(cols53[1]?.startsWith('https://app.example.com/')).toBe(true);
      expect(mainUrl(collectTerminalUrlSegments(cols53, 0, cols53.length, 53))).toBe(OAUTH_URL);
      // At least one width in the sweep must hit the scheme-leading-continuation shape.
      expect(schemeLeadingContinuations).toBeGreaterThan(0);
    });

    test('embedded scheme after ?u= and &next= also survives wrap-at-scheme', () => {
      const cases = [
        {
          line: 'see https://x.example.com/out?u=https://y.example.com/in&k=1',
          url: 'https://x.example.com/out?u=https://y.example.com/in&k=1',
        },
        {
          line: 'go https://x.example.com/a&next=https://y.example.com/b',
          url: 'https://x.example.com/a&next=https://y.example.com/b',
        },
      ];
      for (const c of cases) {
        for (let cols = 20; cols <= 80; cols++) {
          const lines = wrapFixedWidth(c.line, cols);
          if (lines.length < 2) continue;
          const hasSchemeCont = lines.slice(1).some((r) => /^https?:\/\//.test(r.trimStart()));
          if (!hasSchemeCont) continue;
          expect(mainUrl(collectTerminalUrlSegments(lines, 0, lines.length, cols))).toBe(c.url);
        }
      }
    });

    // Direction B — two genuinely unrelated adjacent URLs must NOT be glued.
    // Signal: accumulated URL does NOT end mid-parameter, next row starts with a scheme.
    test('unrelated adjacent URLs stay separate when next row starts with a scheme', () => {
      const a = collectTerminalUrlSegments(
        ['https://a.example.com/xxxxxxxxxxxxxxxx', 'https://b.example.com/y'],
        0,
        2,
        36,
      );
      expect(a.map((m) => m.url)).toEqual([
        'https://a.example.com/xxxxxxxxxxxxxxxx',
        'https://b.example.com/y',
      ]);
      // Explicit anti-glue: no franken-URL spanning both hosts.
      expect(a.some((m) => m.url.includes('a.example.com') && m.url.includes('b.example.com'))).toBe(false);

      // First URL ends mid-token but NOT mid-parameter (=/?/&) — still a new link.
      const b = collectTerminalUrlSegments(
        ['https://example.com/redir?to=aaaaaaa', 'https://target.example.com/final'],
        0,
        2,
        36,
      );
      expect(b.map((m) => m.url)).toEqual([
        'https://example.com/redir?to=aaaaaaa',
        'https://target.example.com/final',
      ]);
      expect(b.some((m) => m.url.includes('redir') && m.url.includes('target.example.com'))).toBe(false);

      // Fixed-width wrap of TWO separate lines (each line is its own complete URL that
      // fills the pane). Not one source line with a space — that can bisect the second
      // scheme into `ttps://…` and is a different failure mode.
      for (let cols = 24; cols <= 48; cols++) {
        const urlA = 'https://a.example.com/' + 'x'.repeat(Math.max(0, cols - 'https://a.example.com/'.length));
        const urlB = 'https://b.example.com/' + 'y'.repeat(Math.max(0, cols - 'https://b.example.com/'.length));
        // Each URL is exactly one pane-width row (or shorter); never wider than cols.
        const lines = [urlA.slice(0, cols), urlB.slice(0, cols)];
        for (const row of lines) expect(row.length).toBeLessThanOrEqual(cols);
        const matches = collectTerminalUrlSegments(lines, 0, lines.length, cols);
        const urls = matches.map((m) => m.url);
        expect(urls.some((u) => u.includes('a.example.com') && u.includes('b.example.com'))).toBe(false);
        expect(urls).toContain(lines[0]);
        expect(urls).toContain(lines[1]);
      }
    });
  });

  test('nested url inside absorbed continuation is not re-emitted (b)', () => {
    const matches = collectTerminalUrlSegments(
      ['https://example.com/redirect?to=aaa', 'x?u=https://target.example.com/f rest'],
      0,
      2,
      36,
    );
    expect(matches).toEqual([
      {
        url: 'https://example.com/redirect?to=aaax?u=https://target.example.com/f',
        segments: [
          { lineIdx: 0, startCol: 0, endCol: 35 },
          { lineIdx: 1, startCol: 0, endCol: 32 },
        ],
      },
    ]);
  });

  test('linearity guard: one match and one segment per row (not n*(n+1)/2)', () => {
    const rows = (n: number) =>
      Array.from({ length: n }, () => 'https://example.com/' + 'a'.repeat(100));

    for (const n of [1000, 2000]) {
      const lines = rows(n);
      const matches = collectTerminalUrlSegments(lines, 0, n, 80);
      expect(matches).toHaveLength(n);
      const totalSegments = matches.reduce((sum, m) => sum + m.segments.length, 0);
      expect(totalSegments).toBe(n);
      // Explicit anti-regression against the old quadratic segment explosion.
      expect(totalSegments).not.toBe((n * (n + 1)) / 2);
      for (let i = 0; i < n; i++) {
        expect(matches[i].url).toBe(lines[i]);
        expect(matches[i].segments).toHaveLength(1);
        expect(matches[i].segments[0].lineIdx).toBe(i);
      }
    }
  });

  test('continuation past endLine still works (seam contract)', () => {
    const lines = ['https://example.com/' + 'a'.repeat(16), 'bbbbbbbb tail'];
    const matches = collectTerminalUrlSegments(lines, 0, 1, 36);
    expect(matches).toHaveLength(1);
    expect(matches[0].segments).toEqual([
      { lineIdx: 0, startCol: 0, endCol: 36 },
      { lineIdx: 1, startCol: 0, endCol: 8 },
    ]);
  });

  test('a link may absorb at most MAX_CONTINUATION_ROWS continuation rows (c)', () => {
    const cols = 80;
    const token = 'a'.repeat(78);
    const lines = ['https://example.com/' + 'a'.repeat(cols - 'https://example.com/'.length)];
    for (let i = 0; i < 399; i++) lines.push(token);
    const matches = collectTerminalUrlSegments(lines, 0, lines.length, cols);
    expect(matches).toHaveLength(1);
    // 1 origin + 128 continuations.
    expect(matches[0].segments).toHaveLength(1 + 128);
  });

  test('tail row keeps its own later URL after absorbed prefix', () => {
    const lines = [
      'https://example.com/' + 'a'.repeat(16),
      'bbbb and also see https://other.example.com/x',
    ];
    const matches = collectTerminalUrlSegments(lines, 0, 2, 36);
    expect(matches).toHaveLength(2);
    expect(matches[0].url).toBe('https://example.com/' + 'a'.repeat(16) + 'bbbb');
    expect(matches[0].segments).toEqual([
      { lineIdx: 0, startCol: 0, endCol: 36 },
      { lineIdx: 1, startCol: 0, endCol: 4 },
    ]);
    expect(matches[1].url).toBe('https://other.example.com/x');
    expect(matches[1].segments).toEqual([
      { lineIdx: 1, startCol: 18, endCol: 45 },
    ]);
  });
});

describe('findTerminalUrlAtCell', () => {
  test('returns the url when the cell is inside a single-line match', () => {
    const rawLines = ['open https://example.com/path/to/resource'];

    expect(findTerminalUrlAtCell(rawLines, 0, 8, 80)).toBe('https://example.com/path/to/resource');
    expect(findTerminalUrlAtCell(rawLines, 0, 4, 80)).toBeNull();
  });

  test('hits wrapped continuation segments', () => {
    const rawLines = [
      'https://example.com/very',
      'longsegmentthatcontinues',
    ];

    expect(findTerminalUrlAtCell(rawLines, 1, 5, 20)).toBe('https://example.com/verylongsegmentthatcontinues');
    expect(findTerminalUrlAtCell(rawLines, 1, 24, 20)).toBeNull();
  });

  test('excludes trailing punctuation from hit testing', () => {
    const rawLines = ['check https://example.com/path.'];

    expect(findTerminalUrlAtCell(rawLines, 0, 10, 80)).toBe('https://example.com/path');
    expect(findTerminalUrlAtCell(rawLines, 0, 30, 80)).toBeNull();
  });
});
