export const DEFAULT_APP_LABELS = Object.freeze({
    hubTitle: 'TERMINALS',
    hubCount: (count) => `${count} ${count === 1 ? 'session' : 'sessions'}`,
    gridNew: '+ terminal',
    gridEmpty: 'No sessions yet — tap + terminal to start one',
    gridLoading: 'Loading sessions…',
    gridAll: 'ALL',
    gridSearchLabel: 'Search sessions',
    gridSearchPlaceholder: 'Search sessions',
    gridGroup: 'Group',
    gridUngrouped: 'Ungrouped',
    launchTitle: 'New terminal',
    launchHint: 'Pick an agent — permissions and model are injected into the launch command.',
    launchContext: 'Workspace',
    launchPermission: 'Permissions',
    launchModel: 'Model',
    launchAction: 'Launch',
    launchBusy: '⏳ Opening session…',
    launchFailed: (message) => `Launch failed: ${message}`,
    hudBack: 'Back',
    hudChip: 'TMUX',
    hudConnected: 'connected',
    hudOffline: 'offline',
    terminalAria: (session) => `Terminal ${session}`,
    fabAria: 'Actions',
    actionType: '⌨ Type',
    actionUpload: '📎 Attach files',
    actionUploading: '⏳ Uploading…',
    actionDpad: '✛ Arrows',
    actionCopy: '⧉ Copy screen',
    actionShortcuts: '⚡ Shortcuts…',
    actionTheme: '🎨 Theme',
    actionFontUp: 'A+ Bigger text',
    actionFontDown: 'A− Smaller text',
    scrollNewContent: 'New content',
    scrollBottom: 'Scroll to bottom',
    uploadFailed: (message) => `Upload failed: ${message}`,
    noteEmpty: 'No note for this session yet',
    noteEdit: '✎ edit',
    noteSave: 'save',
    noteCancel: 'cancel',
    promptsTitle: 'RECENT PROMPTS — tap to edit/resend',
    promptsLoading: 'scanning…',
    promptsEmpty: 'no prompts found yet',
    shortcutsTitle: 'SHORTCUTS',
    shortcutAdd: '+ add',
    shortcutLabel: 'label',
    shortcutSend: 'sends',
    shortcutDelete: '✕',
    shortcutUp: '↑',
    shortcutDown: '↓',
    themeTitle: 'THEME',
    themeBackground: 'Background',
    themeDark: '☾ Dark',
    themeLight: '☀ Light',
    themeDefault: 'Default',
    themeCustom: 'Pick',
    composerCompose: 'COMPOSE',
    composerDirect: 'DIRECT',
    composerHintCompose: 'Draft first, then hit SEND',
    composerHintDirect: 'Keyboard goes straight to the terminal',
    composerPlaceholder: 'Type a prompt… (the box grows with your text)',
    composerSend: 'SEND',
    composerDirectAria: 'Send keys directly to the terminal',
    close: 'Close',
});
